name: Dependabot

on:
  push:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependabot
        uses: dependabot/dependabot@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
