name: Dependabot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
